import { db } from "../server/db";
import { providers } from "../shared/schema";
import { eq, and } from "drizzle-orm";

const jcFamiliesProviders = [
  {
    name: "The Hudson School",
    description: "A learning community where individual talents are celebrated. The small size provides teachers a chance to be creative, collaborate, and experiment with the curriculum. They believe in courage, compassion, and commitment. Provides a rigorous and relevant college-preparatory education that inspires independent thinking and intellectual risk-taking. Offers PreK to 12th grade.",
    address: "601 Park Ave",
    borough: "Hoboken",
    city: "Hoboken",
    state: "NJ",
    zipCode: "07030",
    phone: "201-659-8335",
    website: "https://www.thehudsonschool.org/",
    type: "school" as const,
    ageRangeMin: 4,
    ageRangeMax: 18,
    monthlyPrice: "0",
  },
  {
    name: "The Brunswick School",
    description: "Provides a safe, nurturing, and inspiring learning environment and holistic education that considers children's physical, cognitive, social/emotional, language, and life-skill development. Uses an adaptable curriculum that meets the unique needs of each child. Celebrates the diversity of Jersey City with meaningful community connections.",
    address: "371 7th Street",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-478-8886",
    email: "admissions@thebrunswickschool.com",
    website: "http://thebrunswickschool.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 5,
    hoursOpen: "7:30 AM",
    hoursClose: "6:30 PM",
    monthlyPrice: "0",
  },
  {
    name: "Smart Start Academy - Newark Ave",
    description: "At Smart Start Academy, the goal is to foster a nurturing, safe, fun, and active environment for students to learn and express themselves socially, creatively, emotionally, and intelligently. Offers infant, toddler, preschool, pre-kindergarten, and after-school programs.",
    address: "180 Newark Avenue",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-461-6262",
    website: "https://smart-startacademy.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 12,
    hoursOpen: "7:00 AM",
    hoursClose: "7:00 PM",
    monthlyPrice: "0",
  },
  {
    name: "Smart Start Academy - Heights",
    description: "At Smart Start Academy, the goal is to foster a nurturing, safe, fun, and active environment for students to learn and express themselves socially, creatively, emotionally, and intelligently. Offers infant, toddler, preschool, pre-kindergarten, and after-school programs.",
    address: "462 Central Ave",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07307",
    phone: "201-461-6161",
    website: "https://smart-startacademy.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 12,
    hoursOpen: "7:00 AM",
    hoursClose: "7:00 PM",
    monthlyPrice: "0",
  },
  {
    name: "Smart Start Academy - Jersey Avenue",
    description: "At Smart Start Academy, the goal is to foster a nurturing, safe, fun, and active environment for students to learn and express themselves socially, creatively, emotionally, and intelligently. Offers infant, toddler, preschool, pre-kindergarten, and after-school programs.",
    address: "532 Jersey Avenue",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-461-0101",
    website: "https://smart-startacademy.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 12,
    hoursOpen: "7:00 AM",
    hoursClose: "7:00 PM",
    monthlyPrice: "0",
  },
  {
    name: "Smart Start Academy - Hoboken",
    description: "At Smart Start Academy, the goal is to foster a nurturing, safe, fun, and active environment for students to learn and express themselves socially, creatively, emotionally, and intelligently. Offers infant, toddler, preschool, pre-kindergarten, and after-school programs.",
    address: "552 9th Street",
    borough: "Hoboken",
    city: "Hoboken",
    state: "NJ",
    zipCode: "07030",
    phone: "201-461-6363",
    website: "https://smart-startacademy.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 12,
    hoursOpen: "7:00 AM",
    hoursClose: "7:00 PM",
    monthlyPrice: "0",
  },
  {
    name: "The Waldo School",
    description: "Inquiry-based educational approach provides every opportunity for children to ask questions, grow, think critically, develop, collaborate, and express themselves differently. Students pursue their talents and dreams through a comprehensive academic program. Emphasis on S.T.E.A.M (Science, Technology, Engineering, Arts, Mathematics). Offers preschool, elementary, and middle school.",
    address: "110 1st Street",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-721-6000",
    email: "contact@waldoschool.com",
    website: "https://waldoschool.com/",
    type: "school" as const,
    ageRangeMin: 3,
    ageRangeMax: 14,
    monthlyPrice: "0",
  },
  {
    name: "Ivy Primary Prep",
    description: "An early childhood education center catering to ages 18 months through 6 years. Focuses on primary learning and early childhood development with academically focused programs. Takes an innovative approach to whole student development emphasizing physical, social, and emotional components. Each classroom is capped at ten students for maximum engagement.",
    address: "675 Monmouth St",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07310",
    phone: "201-743-9190",
    email: "info@ivyprimaryprep.com",
    website: "https://www.ivyprimaryprep.com/",
    type: "daycare" as const,
    ageRangeMin: 1,
    ageRangeMax: 6,
    capacity: 10,
    monthlyPrice: "0",
  },
  {
    name: "The French American Academy - Jersey City",
    description: "Provides a bilingual and comprehensive curriculum in an atmosphere that encourages critical reasoning, wonder, enthusiasm, and strong ambition. Serves students from 2.5 to 14 years of age. Believes learning a second language early is a lifelong advantage. Impressive teacher-student ratios: 5:1 for Pre-K, 8:1 for three-year-olds, 10:1 for four-year-olds, 12:1 for Kindergarten and up.",
    address: "209 Third Street",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-338-8320",
    email: "admissions@faacademy.org",
    website: "https://faacademy.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 14,
    monthlyPrice: "0",
  },
  {
    name: "Academy of Excellence",
    description: "A prestigious early learning center led by Dorota Mani for over a decade. Dedicated team of educators brings experience and passion for teaching. Serves infants, toddlers, preschoolers, kindergartners, and first graders. Believes in nourishing curiosity and creating windows of opportunity for young minds. Accredited curriculum infused with STEAM, small class sizes, and dedicated teachers.",
    address: "159 2nd Street",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-963-5555",
    website: "https://academyofexcellencepreschool.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 7,
    monthlyPrice: "0",
  },
  {
    name: "Waterfront Montessori",
    description: "Uses a Montessori curriculum for toddlers through grade 5, and a combined Montessori and International Baccalaureate (IB) curriculum for grades 6 through 8. Student-to-teacher ratios: 1:4 for toddlers, 1:10 for primary and lower elementary, 1:8 for upper elementary and middle school. Students are exposed to visual and fine arts, choral and instrumental music, theater, and music appreciation.",
    address: "150 Warren St",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-333-5600",
    email: "info@waterfrontmontessori.com",
    website: "http://www.waterfrontmontessori.com/",
    type: "school" as const,
    ageRangeMin: 1,
    ageRangeMax: 14,
    monthlyPrice: "0",
  },
  {
    name: "Learning Ladders - Paulus Hook",
    description: "International Baccalaureate World School offering care for infants from 2 months to classes for 6-year-old kids. Fosters independence and promotes analytical thinking and creative problem-solving. Open M-F throughout the year with flexible schedules and fewest closings. Weekly enrichment classes and digital daily reports sent to each family.",
    address: "33-35 Hudson St",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-918-6643",
    email: "admissions@learningladersnj.com",
    website: "http://www.learningladdersnj.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 6,
    hoursOpen: "7:30 AM",
    hoursClose: "6:30 PM",
    monthlyPrice: "0",
  },
  {
    name: "Learning Ladders - Grove Street",
    description: "International Baccalaureate World School offering care for infants from 2 months to classes for 6-year-old kids. Fosters independence and promotes analytical thinking and creative problem-solving. Open M-F throughout the year with flexible schedules and fewest closings. Weekly enrichment classes and digital daily reports sent to each family.",
    address: "160 Morgan St, Suite #2",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-918-6643",
    email: "admissions@learningladersnj.com",
    website: "http://www.learningladdersnj.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 6,
    hoursOpen: "7:30 AM",
    hoursClose: "6:30 PM",
    monthlyPrice: "0",
  },
  {
    name: "Bright Horizons - Harborside",
    description: "Located in the lobby of Plaza 3 in Harborside Financial Center. Uses curriculum titled 'The World at Their Fingertips' designed to engage children in active learning while helping them learn, grow, and develop. Encourages a spirit of community. Children are served healthy food and eat family-style. Offers flexible 2, 3, 4, or 5-day options.",
    address: "152 Plaza 3",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07311",
    phone: "201-661-2696",
    website: "https://child-care-preschool.brighthorizons.com/nj/jerseycity/plaza3jc",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 6,
    hoursOpen: "7:00 AM",
    hoursClose: "6:30 PM",
    monthlyPrice: "0",
  },
  {
    name: "Bright Horizons - Maxwell Lane",
    description: "Uses curriculum titled 'The World at Their Fingertips' designed to engage children in active learning while helping them learn, grow, and develop. Encourages a spirit of community. Children are served healthy food and eat family-style. Offers flexible 2, 3, 4, or 5-day options.",
    address: "1102 Maxwell Lane",
    borough: "Hoboken",
    city: "Hoboken",
    state: "NJ",
    zipCode: "07030",
    phone: "877-624-4532",
    website: "https://child-care-preschool.brighthorizons.com/nj/hoboken/maxwellplace",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 6,
    hoursOpen: "7:00 AM",
    hoursClose: "6:30 PM",
    monthlyPrice: "0",
  },
  {
    name: "Bright Horizons - Sinatra Drive",
    description: "Uses curriculum titled 'The World at Their Fingertips' designed to engage children in active learning while helping them learn, grow, and develop. Encourages a spirit of community. Children are served healthy food and eat family-style. Offers flexible 2, 3, 4, or 5-day options.",
    address: "Sinatra Drive",
    borough: "Hoboken",
    city: "Hoboken",
    state: "NJ",
    zipCode: "07030",
    phone: "877-624-4532",
    website: "https://child-care-preschool.brighthorizons.com/nj/hoboken/sinatradrive",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 6,
    hoursOpen: "7:00 AM",
    hoursClose: "6:30 PM",
    monthlyPrice: "0",
  },
  {
    name: "Early Beginnings Day School - Toddler/Pre-K Center",
    description: "Provides services for children ages 0 months through 5 years old. Provides a safe, caring, and enriched environment that promotes learning and the development of each child. Before-school programs, after-school programs, and half-day programs are available.",
    address: "109 Christopher Columbus Dr",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-685-3457",
    website: "https://www.earlybeginningsdayschool.org/",
    type: "daycare" as const,
    ageRangeMin: 1,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Early Beginnings Day School - Infant Center",
    description: "Provides services for infants ages 0-12 months. Provides a safe, caring, and enriched environment that promotes learning and the development of each child.",
    address: "338 Grove Street",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-685-3457",
    website: "https://www.earlybeginningsdayschool.org/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 1,
    monthlyPrice: "0",
  },
  {
    name: "The Garden Preschool Cooperative",
    description: "Provides high-quality education for children ages 3 through 5 with a theme-based curriculum that changes year to year. A parent-run non-profit preschool using the developmental-interactive approach pioneered by Bank Street Graduate School of Education. Parents play a central role in education, help enrich curriculum, offer guidance to teachers, and assist in the classroom once a month.",
    address: "242 10th Street",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    email: "enrollment@gardenpreschoolcooperative.org",
    website: "https://gardenpreschoolcoop.org/",
    type: "daycare" as const,
    ageRangeMin: 3,
    ageRangeMax: 5,
    hoursOpen: "8:30 AM",
    hoursClose: "4:00 PM",
    monthlyPrice: "0",
  },
  {
    name: "Hamilton Park Montessori School",
    description: "Educates children from toddlers through 8th grade by nurturing the whole child and their innate love of learning. Vision: creating a better world through respectful people who are authentic to themselves, passionate in their pursuits, and connected to the world around them. Students engage in Movement/PE, Music, Art, Spanish, Literacy, Writers' & Readers' Workshop, and more.",
    address: "1 McWilliams Place",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-533-1910",
    email: "admissions@hpmsjc.com",
    website: "http://www.hamiltonparkmontessori.com/",
    type: "school" as const,
    ageRangeMin: 1,
    ageRangeMax: 14,
    hoursOpen: "8:00 AM",
    hoursClose: "6:00 PM",
    monthlyPrice: "0",
  },
  {
    name: "Hudson Montessori School",
    description: "A Montessori school serving the Jersey City community with authentic Montessori education. Children learn through hands-on activities and self-directed exploration in a prepared environment designed to foster independence, concentration, and a love of learning.",
    address: "10 Regent Street",
    borough: "Jersey City",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    phone: "201-516-0700",
    website: "https://hudsonmontessori.com/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 12,
    monthlyPrice: "0",
  },
];

async function importProviders() {
  console.log(`Starting import of ${jcFamiliesProviders.length} providers from JCFamilies...`);
  
  let imported = 0;
  let skipped = 0;
  
  for (const provider of jcFamiliesProviders) {
    try {
      // Check if provider already exists by name and address
      const existing = await db.select()
        .from(providers)
        .where(
          and(
            eq(providers.name, provider.name),
            eq(providers.address, provider.address)
          )
        );
      
      if (existing.length > 0) {
        console.log(`Skipping duplicate: ${provider.name}`);
        skipped++;
        continue;
      }
      
      await db.insert(providers).values({
        ...provider,
        isActive: true,
        isVerified: false, // Not government verified, user-submitted
        claimStatus: 'unclaimed',
        profileCompleteness: 60,
        isProfileVisible: true,
      });
      
      console.log(`Imported: ${provider.name}`);
      imported++;
    } catch (error) {
      console.error(`Error importing ${provider.name}:`, error);
    }
  }
  
  console.log(`\nImport complete!`);
  console.log(`Imported: ${imported}`);
  console.log(`Skipped (duplicates): ${skipped}`);
}

importProviders()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Import failed:", error);
    process.exit(1);
  });
