import { db } from "../server/db";
import { providers } from "../shared/schema";
import { eq } from "drizzle-orm";

const manhattanPreschools = [
  {
    name: "Barrow Street Nursery School",
    description: "Part of Greenwich House Pottery, offering a nurturing early childhood education environment in the heart of Greenwich Village. Combines creative arts with foundational learning.",
    address: "27 Barrow Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10014",
    website: "http://www.greenwichhousepottery.org/nursery_school/index",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Bright Horizons at 20 Pine",
    description: "Full-service child care and early education center in the Financial District. Offers infant, toddler, preschool, and pre-K programs with experienced educators.",
    address: "20 Pine Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10005",
    phone: "212-509-1580",
    website: "https://child-care-preschool.brighthorizons.com/ny/newyork/20pine",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Bright Beginnings NYC Preschool",
    description: "A welcoming preschool environment focused on early childhood development and school readiness in Lower Manhattan.",
    address: "80 Beekman Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10038",
    phone: "347-948-7130",
    website: "http://brightbeginningsnyc.com/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Brotherhood Synagogue Nursery School",
    description: "A warm and nurturing nursery school located in historic Gramercy Park, providing quality early childhood education in a welcoming community environment.",
    address: "28 Gramercy Park South",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10003",
    phone: "212-995-9867",
    website: "https://www.brotherhoodnursery.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Chelsea Day School",
    description: "Progressive preschool and elementary school offering child-centered education that nurtures creativity, critical thinking, and social-emotional development.",
    address: "319 5th Avenue",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10016",
    website: "https://www.chelseadayschool.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 10,
    monthlyPrice: "0",
  },
  {
    name: "KinderCare at New York Plaza",
    description: "Full-service early education and child care center in the Financial District. Offers programs for infants through pre-K with a focus on school readiness.",
    address: "4 NY Plaza, Suite 104",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10004",
    phone: "212-513-7367",
    website: "https://www.kindercare.com/our-centers/new-york/ny/081037",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Church Street School for Music and Art",
    description: "Unique preschool combining early childhood education with music and art instruction. Children learn through creative expression in a nurturing environment in TriBeCa.",
    address: "74 Warren Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10007",
    phone: "212-571-7290",
    website: "http://churchstreetschool.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Downing Street Playgroup",
    description: "A cooperative playgroup in Greenwich Village offering a warm, nurturing environment where children learn through play and exploration.",
    address: "32 Carmine Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10014",
    phone: "212-924-2557",
    website: "https://www.downingstreetplaygroup.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 4,
    monthlyPrice: "0",
  },
  {
    name: "Educational Alliance Preschool",
    description: "Part of the historic Educational Alliance on the Lower East Side, offering quality early childhood education with a focus on social-emotional development and school readiness.",
    address: "197 E. Broadway",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10002",
    phone: "646-395-4250",
    website: "https://edalliance.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Elements Preschool",
    description: "Progressive preschool on the Lower East Side offering a play-based curriculum that fosters creativity, critical thinking, and social-emotional growth.",
    address: "99 Suffolk St",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10002",
    phone: "212-982-4444",
    website: "http://elementspreschool.com/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "FedKids Child Care Center",
    description: "Child care center managed by Bright Horizons, located at Federal Plaza. Serves federal employees and the local community with quality early education programs.",
    address: "26 Federal Plaza, Room 110",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10278",
    phone: "212-264-4277",
    website: "http://child-care-preschool.brighthorizons.com/NY/NewYork/fedkids/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "HGL ART Preschool and Fine Arts",
    description: "Art-focused preschool in Union Square area offering early childhood education integrated with fine arts instruction. Nurtures creativity and artistic expression.",
    address: "21 E. 13th Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10003",
    phone: "646-682-7887",
    website: "https://hglart.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "My Little School",
    description: "Intimate preschool in TriBeCa offering personalized early childhood education in a warm, nurturing environment. Focus on creative play and school readiness.",
    address: "54 Reade Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10007",
    phone: "212-566-6764",
    website: "https://www.mylittleschoolnyc.com/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "New Amsterdam School",
    description: "Progressive elementary school in the East Village offering an innovative approach to education that emphasizes creativity, critical thinking, and community.",
    address: "62 Avenue B",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10009",
    phone: "212-533-1820",
    website: "https://www.newamsterdamschool.org/",
    type: "school" as const,
    ageRangeMin: 4,
    ageRangeMax: 11,
    monthlyPrice: "0",
  },
  {
    name: "New York Preschool - Battery Park City",
    description: "Quality early childhood education center in Battery Park City offering programs for toddlers through pre-K in a modern, well-equipped facility.",
    address: "393 South End Avenue",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10282",
    phone: "212-991-3000",
    website: "https://www.nypre.com/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "New York Preschool - TriBeCa",
    description: "Quality early childhood education center in TriBeCa offering programs for toddlers through pre-K with experienced educators and engaging curriculum.",
    address: "88 Leonard Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10013",
    phone: "212-334-3301",
    website: "https://www.nypre.com/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Nord Anglia International School New York",
    description: "Premium international school offering world-class education from preschool through high school. Features global curriculum and exceptional facilities.",
    address: "44 E 2nd St",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10003",
    phone: "212-600-2010",
    website: "http://www.nordangliaeducation.com/our-schools/new-york",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 18,
    monthlyPrice: "0",
  },
  {
    name: "Perry School",
    description: "Intimate nursery school in the West Village offering a warm, nurturing environment with a focus on social-emotional development and creative play.",
    address: "136 West 10th Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10014",
    phone: "212-255-1685",
    website: "http://www.perryschool.com/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Playto Tribeca Childcare",
    description: "Modern childcare center in TriBeCa offering flexible care options with a focus on play-based learning and child development.",
    address: "90 Hudson Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10013",
    phone: "212-590-2445",
    website: "https://playto.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Playto Battery Park Childcare",
    description: "Modern childcare center in Battery Park City offering flexible care options with a focus on play-based learning and early childhood development.",
    address: "2 S End Ave",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10280",
    phone: "212-590-2445",
    website: "https://playto.com/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Reade Street Prep",
    description: "Preschool in TriBeCa offering quality early childhood education with a focus on school readiness and foundational learning skills.",
    address: "77 Reade Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10007",
    phone: "212-513-7735",
    website: "",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Third Street Preschool",
    description: "Community preschool in the East Village offering play-based early childhood education that nurtures the whole child - socially, emotionally, and intellectually.",
    address: "235 East 11 Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10003",
    phone: "212-777-3240",
    website: "http://www.thirdstreet.nyc/preschool",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Transfiguration School",
    description: "Catholic elementary school in Chinatown offering quality education rooted in faith and values. Serves the diverse Lower Manhattan community.",
    address: "10 Confucius Plaza",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10002",
    phone: "212-431-8769",
    website: "https://www.transfigurationschoolnyc.org/",
    type: "school" as const,
    ageRangeMin: 4,
    ageRangeMax: 14,
    monthlyPrice: "0",
  },
  {
    name: "The First Presbyterian Nursery School",
    description: "Warm and nurturing nursery school in Greenwich Village offering a play-based curriculum that fosters creativity, curiosity, and social-emotional development.",
    address: "12 West 12th Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10011",
    phone: "212-691-3432",
    website: "http://www.fpcns.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "The Montessori in SoHo",
    description: "Authentic Montessori preschool in SoHo offering child-centered education that nurtures independence, curiosity, and a love of learning.",
    address: "75 Sullivan Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10012",
    phone: "212-633-0600",
    website: "http://www.themontessorischools.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 6,
    monthlyPrice: "0",
  },
  {
    name: "University Settlement Early Childhood Center",
    description: "Quality early childhood education center on the Lower East Side, part of the historic University Settlement. Serves diverse families with affordable, nurturing care.",
    address: "184 Eldridge Street",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10002",
    phone: "212-453-4584",
    website: "https://www.universitysettlement.org/us/programs/early_childhood/early_childhood_center/",
    type: "daycare" as const,
    ageRangeMin: 0,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
  {
    name: "Ya-Ya Preschool",
    description: "Preschool in TriBeCa offering bilingual early childhood education with a focus on creativity, exploration, and cultural awareness.",
    address: "291 Broadway",
    borough: "Manhattan",
    city: "New York",
    state: "NY",
    zipCode: "10013",
    phone: "646-727-0718",
    website: "http://yayapreschool.org/",
    type: "school" as const,
    ageRangeMin: 2,
    ageRangeMax: 5,
    monthlyPrice: "0",
  },
];

async function importManhattanPreschools() {
  console.log(`Starting import of ${manhattanPreschools.length} Downtown Manhattan preschools from HRP Mamas...`);
  
  let imported = 0;
  let skipped = 0;
  
  for (const school of manhattanPreschools) {
    try {
      const existing = await db.select()
        .from(providers)
        .where(eq(providers.name, school.name));
      
      if (existing.length > 0) {
        console.log(`Skipping duplicate: ${school.name}`);
        skipped++;
        continue;
      }
      
      await db.insert(providers).values({
        ...school,
        isActive: true,
        isVerified: false,
        claimStatus: 'unclaimed',
        profileCompleteness: 60,
        isProfileVisible: true,
      });
      
      console.log(`Imported: ${school.name}`);
      imported++;
    } catch (error) {
      console.error(`Error importing ${school.name}:`, error);
    }
  }
  
  console.log(`\nImport complete!`);
  console.log(`Imported: ${imported}`);
  console.log(`Skipped (duplicates): ${skipped}`);
}

importManhattanPreschools()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Import failed:", error);
    process.exit(1);
  });
